"""added messages to responses

Revision ID: cac5e85054bf
Revises: 6e88e5d5abf3
Create Date: 2023-07-13 14:35:05.581865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cac5e85054bf'
down_revision = '6e88e5d5abf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('responses', sa.Column('message', sa.String(), nullable=True, comment='Сопроводительное письмо'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('responses', 'message')
    # ### end Alembic commands ###
